import Link from "next/link";
import { requireUser } from "@/lib/auth/session";
import { listAdvertiserAds } from "@/lib/db/ads";
import { PAYMENT_LABELS, STATUS_LABELS } from "@/lib/ads/types";

export default async function AdvertiserPage() {
  const user = await requireUser();
  const ads = await listAdvertiserAds(user.id);
  return <main className="mx-auto max-w-5xl px-6 py-12"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-sky-700">ADVERTISER</p><h1 className="mt-2 text-3xl font-semibold">広告記事・契約管理</h1><p className="mt-3 text-slate-600">広告記事ごとに、掲載状況とStripeの月額契約を確認できます。</p></div><Link href="/advertiser/ads/new" className="rounded-full bg-sky-700 px-5 py-3 text-center font-semibold text-white">新しい広告記事を申し込む</Link></div>
  <section className="mt-8 grid gap-5">{ads.length ? ads.map((ad) => <article key={ad.adId} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-start"><div><p className="text-sm text-slate-500">{ad.companyName}</p><h2 className="mt-1 text-xl font-semibold text-slate-950">{ad.title}</h2><div className="mt-5 flex flex-wrap gap-3"><Link href={`/advertiser/ads/${ad.adId}`} className="rounded-full bg-sky-700 px-5 py-2 text-sm font-semibold text-white hover:bg-sky-800">詳細・契約管理</Link>{ad.status === "published" && ad.microCmsContentId ? <Link href={`/articles/${ad.microCmsContentId}`} className="rounded-full border border-slate-300 px-5 py-2 text-sm font-semibold text-slate-700 hover:border-sky-500 hover:text-sky-700">記事を見る</Link> : null}</div></div><dl className="grid min-w-64 grid-cols-[auto_1fr] gap-x-5 gap-y-2 text-sm"><dt className="text-slate-500">掲載状況</dt><dd className="font-medium">{STATUS_LABELS[ad.status]}</dd><dt className="text-slate-500">支払状況</dt><dd>{PAYMENT_LABELS[ad.paymentStatus]}</dd><dt className="text-slate-500">月額</dt><dd>{ad.monthlyAmount.toLocaleString("ja-JP")}円（税込）</dd><dt className="text-slate-500">次回更新・終了</dt><dd>{ad.currentPeriodEnd ? new Date(ad.currentPeriodEnd).toLocaleDateString("ja-JP") : "—"}</dd></dl></div></article>) : <div className="rounded-2xl bg-white p-8 text-slate-600 ring-1 ring-slate-200"><p className="font-semibold text-slate-900">申し込み済みの広告記事はありません</p><p className="mt-2 text-sm">新しい広告記事を作成すると、この記事専用のStripe月額契約を申し込めます。</p></div>}</section></main>;
}
